smtp:
  addr: ':1025'
  domain: 'localhost'
  login: 'smtp_login'
  password: 'smtp_password'
amqp:
  login: 'guest'
  password: 'guest'
  host: 'localhost'
  port: 5672
  virtual_host: ''
  routing_key: ''
http:
  addr: ':1333'
domains:
  example.com: example_com
  example2.com: example2_com
